/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Device } from "./Device";
import { DeviceCountArgs } from "./DeviceCountArgs";
import { DeviceFindManyArgs } from "./DeviceFindManyArgs";
import { DeviceFindUniqueArgs } from "./DeviceFindUniqueArgs";
import { CreateDeviceArgs } from "./CreateDeviceArgs";
import { UpdateDeviceArgs } from "./UpdateDeviceArgs";
import { DeleteDeviceArgs } from "./DeleteDeviceArgs";
import { DeviceService } from "../device.service";
@graphql.Resolver(() => Device)
export class DeviceResolverBase {
  constructor(protected readonly service: DeviceService) {}

  async _devicesMeta(
    @graphql.Args() args: DeviceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Device])
  async devices(@graphql.Args() args: DeviceFindManyArgs): Promise<Device[]> {
    return this.service.devices(args);
  }

  @graphql.Query(() => Device, { nullable: true })
  async device(
    @graphql.Args() args: DeviceFindUniqueArgs
  ): Promise<Device | null> {
    const result = await this.service.device(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Device)
  async createDevice(@graphql.Args() args: CreateDeviceArgs): Promise<Device> {
    return await this.service.createDevice({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Device)
  async updateDevice(
    @graphql.Args() args: UpdateDeviceArgs
  ): Promise<Device | null> {
    try {
      return await this.service.updateDevice({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Device)
  async deleteDevice(
    @graphql.Args() args: DeleteDeviceArgs
  ): Promise<Device | null> {
    try {
      return await this.service.deleteDevice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
