/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Media as PrismaMedia,
  Session as PrismaSession,
} from "@prisma/client";

export class MediaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MediaCountArgs, "select">): Promise<number> {
    return this.prisma.media.count(args);
  }

  async mediaItems<T extends Prisma.MediaFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MediaFindManyArgs>
  ): Promise<PrismaMedia[]> {
    return this.prisma.media.findMany<Prisma.MediaFindManyArgs>(args);
  }
  async media<T extends Prisma.MediaFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MediaFindUniqueArgs>
  ): Promise<PrismaMedia | null> {
    return this.prisma.media.findUnique(args);
  }
  async createMedia<T extends Prisma.MediaCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MediaCreateArgs>
  ): Promise<PrismaMedia> {
    return this.prisma.media.create<T>(args);
  }
  async updateMedia<T extends Prisma.MediaUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MediaUpdateArgs>
  ): Promise<PrismaMedia> {
    return this.prisma.media.update<T>(args);
  }
  async deleteMedia<T extends Prisma.MediaDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MediaDeleteArgs>
  ): Promise<PrismaMedia> {
    return this.prisma.media.delete(args);
  }

  async findSessions(
    parentId: string,
    args: Prisma.SessionFindManyArgs
  ): Promise<PrismaSession[]> {
    return this.prisma.media
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sessions(args);
  }
}
