/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MediaService } from "../media.service";
import { MediaCreateInput } from "./MediaCreateInput";
import { Media } from "./Media";
import { MediaFindManyArgs } from "./MediaFindManyArgs";
import { MediaWhereUniqueInput } from "./MediaWhereUniqueInput";
import { MediaUpdateInput } from "./MediaUpdateInput";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { SessionWhereUniqueInput } from "../../session/base/SessionWhereUniqueInput";

export class MediaControllerBase {
  constructor(protected readonly service: MediaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Media })
  async createMedia(@common.Body() data: MediaCreateInput): Promise<Media> {
    return await this.service.createMedia({
      data: data,
      select: {
        createdAt: true,
        duration: true,
        filePath: true,
        fileStoragePath: true,
        id: true,
        linkedSession: true,
        mediaDuration: true,
        mediaType: true,
        relatedSession: true,
        storagePath: true,
        totalDuration: true,
        typeOfMedia: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Media] })
  @ApiNestedQuery(MediaFindManyArgs)
  async mediaItems(@common.Req() request: Request): Promise<Media[]> {
    const args = plainToClass(MediaFindManyArgs, request.query);
    return this.service.mediaItems({
      ...args,
      select: {
        createdAt: true,
        duration: true,
        filePath: true,
        fileStoragePath: true,
        id: true,
        linkedSession: true,
        mediaDuration: true,
        mediaType: true,
        relatedSession: true,
        storagePath: true,
        totalDuration: true,
        typeOfMedia: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Media })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async media(
    @common.Param() params: MediaWhereUniqueInput
  ): Promise<Media | null> {
    const result = await this.service.media({
      where: params,
      select: {
        createdAt: true,
        duration: true,
        filePath: true,
        fileStoragePath: true,
        id: true,
        linkedSession: true,
        mediaDuration: true,
        mediaType: true,
        relatedSession: true,
        storagePath: true,
        totalDuration: true,
        typeOfMedia: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Media })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMedia(
    @common.Param() params: MediaWhereUniqueInput,
    @common.Body() data: MediaUpdateInput
  ): Promise<Media | null> {
    try {
      return await this.service.updateMedia({
        where: params,
        data: data,
        select: {
          createdAt: true,
          duration: true,
          filePath: true,
          fileStoragePath: true,
          id: true,
          linkedSession: true,
          mediaDuration: true,
          mediaType: true,
          relatedSession: true,
          storagePath: true,
          totalDuration: true,
          typeOfMedia: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Media })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMedia(
    @common.Param() params: MediaWhereUniqueInput
  ): Promise<Media | null> {
    try {
      return await this.service.deleteMedia({
        where: params,
        select: {
          createdAt: true,
          duration: true,
          filePath: true,
          fileStoragePath: true,
          id: true,
          linkedSession: true,
          mediaDuration: true,
          mediaType: true,
          relatedSession: true,
          storagePath: true,
          totalDuration: true,
          typeOfMedia: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/sessions")
  @ApiNestedQuery(SessionFindManyArgs)
  async findSessions(
    @common.Req() request: Request,
    @common.Param() params: MediaWhereUniqueInput
  ): Promise<Session[]> {
    const query = plainToClass(SessionFindManyArgs, request.query);
    const results = await this.service.findSessions(params.id, {
      ...query,
      select: {
        createdAt: true,
        endTime: true,
        id: true,

        media: {
          select: {
            id: true,
          },
        },

        mode: true,
        startTime: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sessions")
  async connectSessions(
    @common.Param() params: MediaWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        connect: body,
      },
    };
    await this.service.updateMedia({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sessions")
  async updateSessions(
    @common.Param() params: MediaWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        set: body,
      },
    };
    await this.service.updateMedia({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sessions")
  async disconnectSessions(
    @common.Param() params: MediaWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        disconnect: body,
      },
    };
    await this.service.updateMedia({
      where: params,
      data,
      select: { id: true },
    });
  }
}
